### ISSUE TITLE
Build IoT platform integration API

### ISSUE THREAD

**Issue by kamran-tuni** [kamran-tuni/smart-rule-engine#7]
URL: /api/v1/integrations/
Body
```
name:
type: Choices: (thingsboard)
base_url:
api_key:
```

Models, Entities
```
Integration
    name:
    type: Choices: (thingsboard)
    base_url:
    api_key:
```

UseCases:
```
CreateIntegration
UpdateIntegration
ListIntegration
RetrieveIntegration
DeleteIntegration
```
